# This file is part of OpenOrienteering.

# Copyright 2021 Kai Pastor
#
# Redistribution and use is allowed according to the terms of the BSD license:
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# 1. Redistributions of source code must retain the copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products 
#    derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

jobs:
- job: Build
  timeoutInMinutes: 120
  variables:
    VCPKG_DOWNLOADS: $(Build.StagingDirectory)/source
    VCPKG_DEFAULT_BINARY_CACHE: $(Build.StagingDirectory)/binary
    VCPKG_FEATURE_FLAGS: registries
    VERBOSE: 1
  strategy:
    maxParallel: 5
    matrix:
      macOS:
        IMAGE_NAME: 'macos-10.15'
        SETUP: 'macos'
        MACOSX_DEPLOYMENT_TARGET: 10.12
      Linux:
        IMAGE_NAME: 'ubuntu-20.04'
        SETUP: 'ubuntu'
      MinGW_x64:
        IMAGE_NAME: 'windows-2019'
        SETUP: 'msys2'
        MINGW: mingw64
        VCPKG_DEFAULT_TRIPLET: x64-mingw-dynamic
        VCPKG_DEFAULT_HOST_TRIPLET: x64-mingw-dynamic
        SUPERBUILD_INSTALL_DIR_NATIVE: 'C:\msys2'
  pool:
    vmImage: '$(IMAGE_NAME)'
  steps:
  - ${{ if eq(variables['Agent.OS'], 'Darwin') }}:
    - template: setup-macos.yml
  - ${{ if eq(variables['Agent.OS'], 'Linux') }}:
    - template: setup-ubuntu.yml
  - ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
    - template: setup-msys2.yml
  - template: build.yml

